title: Don Perri
description: Juego de perrito que tiene que ir pasando niveles para llegar a su fin
template:
  repo: don-perri-template
  name: don-perri
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
